name: ldpl-lang 
base: core22 
version: '5.1.0'
summary: Compiled programming language for Unix systems, inspired by COBOL 
description: |
        The LDPL project produces the LDPL Programming Language, a free, powerful, compiled, open-source programming language designed from the ground up to be excessively expressive, readable, fast and easy to learn. LDPL was designed to run on Unix systems, including AMD-64 Linux, macOS, ARMv8 Linux, Android Termux and both Intel and PowerPC OS X (tested from Tiger 10.4 onwards). It even supports UTF-8 out of the box.

grade: stable 
confinement: classic 

apps:
    ldpl:
     command: bin/ldpl

parts:
  ldpl:
    plugin: autotools
    source: https://github.com/Lartu/ldpl.git
    source-tag: '5.1.0'
    build-packages:
            - g++
            - build-essential
            - make
            - man-db
            - libc6-dev
    override-build: |
            make 
            make install
    organize:
            /usr/local/bin/ldpl: bin/

